import Head from 'next/head';

import { About, Footer, Header, Skills, Testimonial, Work } from '../container';
import Navbar from '../components/Navbar';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <Header />
      <About />
      <Skills />
      <Testimonial />
      <Work />
      <Footer />
    </div>
  );
}
